services:
  idealista-bot:
    container_name: idealista-bot
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro  # Sync container time with host
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    # Security options
    security_opt:
      - no-new-privileges:true
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/data/user_configs.json') or os.path.exists('/tmp/bot_healthy') else 1)"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 120s
