# fly.toml app configuration file for idealista-notifier Telegram bot

app = 'idealista-notifier'
primary_region = 'cdg'

[build]

[env]
  # TELEGRAM_BOT_TOKEN will be set as a secret

# Machine configuration
[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

# Process configuration for background service
[processes]
  app = "python src/bot.py"

# Volume for persistent data storage
[[mounts]]
  source = "data_volume"
  destination = "/app/data"