# fly.toml app configuration file for idealista-notifier Telegram bot
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'idealista-notifier'
primary_region = 'cdg'

[build]

# No HTTP service needed for Telegram bot
# Remove the [http_service] section since this is a background service

[env]
  # Environment variables can be set here or via secrets
  # TELEGRAM_BOT_TOKEN will be set as a secret

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

# Ensure the machine stays running (don't auto-stop)
[processes]
  app = "python src/bot.py"

# Volume for persistent data storage
[[mounts]]
  source = "data_volume"
  destination = "/app/data"
