# fly.toml app configuration file for idealista-notifier Telegram bot
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'idealista-notifier'
primary_region = 'cdg'

[build]

# Environment variables
[env]
  # TELEGRAM_BOT_TOKEN will be set as a secret

# Machine configuration
[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

# Process configuration for background service
[processes]
  app = "python src/bot.py"

# Volume for persistent data storage
[[mounts]]
  source = "data_volume"
  destination = "/app/data"

# Deployment strategy - single machine with auto-restart
[deploy]
  strategy = "immediate"
  max_unavailable = 0

# Restart policy for reliability
[restart]
  policy = "always"
